openapi: 3.0.0
info:
  title: WorktimeRegister API
  description: Worktime Registration API for to monitors working hours of employees on projects.
  version: "1.0"2
servers:
  - url: http://localhost:8080/api/
paths:
  /employee:
    get:
      summary: Returns a list of active employees.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of employees.
    post:
      summary: Saves a new employee.
      description: Saves a new employee with the given name.
      responses:
        '201':
          description: A JSON of the new employee.

          